const CREATE_FAVORITE = 'CREATE_FAVORITE';
const DELETE_FAVORITE = 'DELETE_FAVORITE';
const FETCH_REQUEST = 'FETCH_FAVORITE_REQUEST';
const FETCH_SUCCESS = 'FETCH_FAVORITE_SUCCESS';
const FETCH_FAILD = 'FETCH_FAVORITE_FAILD';

export default {
  CREATE_FAVORITE,
  DELETE_FAVORITE,
  FETCH_REQUEST,
  FETCH_SUCCESS,
  FETCH_FAILD,
};
